# Generated by Django 5.0 on 2024-02-03 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_comment="음식 이름", max_length=50)),
                (
                    "description",
                    models.CharField(db_comment="음식에 대한 설명", max_length=200),
                ),
                (
                    "image_path",
                    models.CharField(db_comment="음식 이미지 경로", max_length=100),
                ),
                ("calorie", models.IntegerField(db_comment="100g당 칼로리")),
                ("carbohydrate", models.IntegerField(db_comment="100g당 탄수화물")),
                ("protein", models.IntegerField(db_comment="100g당 단백질")),
                ("fat", models.IntegerField(db_comment="100g당 지방")),
                ("is_main", models.BooleanField(db_comment="메인 음식 여부", default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        blank=True,
                        db_comment="식단 이미지 경로, 사용자가 직접 추가한 식단이면 null",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("take_at", models.DateField(db_comment="식단을 섭취한 날짜")),
                (
                    "meal",
                    models.IntegerField(
                        db_comment="1은 아침, 2는 점심, 3은 저녁, 4는 간식, 5는 야식", default=1
                    ),
                ),
                (
                    "memo",
                    models.TextField(blank=True, db_comment="식단에 대한 메모", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetailOfDiet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_x",
                    models.IntegerField(
                        blank=True,
                        db_comment="이미지의 x좌표,  사용자가 직접 추가한 식단이면 null",
                        null=True,
                    ),
                ),
                (
                    "image_y",
                    models.IntegerField(
                        blank=True,
                        db_comment="이미지의 y좌표,  사용자가 직접 추가한 식단이면 null",
                        null=True,
                    ),
                ),
                ("name", models.CharField(db_comment="음식 이름", max_length=100)),
                ("carbohydrate", models.IntegerField(db_comment="100g당 탄수화물")),
                ("protein", models.IntegerField(db_comment="100g당 단백질")),
                ("fat", models.IntegerField(db_comment="100g당 지방")),
                ("calorie", models.IntegerField(db_comment="100g당 칼로리")),
                (
                    "quantity",
                    models.IntegerField(db_comment="몇 인분인지, 1: 소, 2: 중, 3: 대"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="diet.userdiet"
                    ),
                ),
            ],
        ),
    ]
