# Generated by Django 5.0 on 2024-02-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0002_alter_detailofdiet_calorie_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="detailofdiet", name="image_x",),
        migrations.RemoveField(model_name="detailofdiet", name="image_y",),
        migrations.AddField(
            model_name="detailofdiet",
            name="image_x_end",
            field=models.IntegerField(
                blank=True, db_comment="이미지의 x 끝좌표,  사용자가 직접 추가한 식단이면 null", null=True
            ),
        ),
        migrations.AddField(
            model_name="detailofdiet",
            name="image_x_start",
            field=models.IntegerField(
                blank=True, db_comment="이미지의 x 시작좌표,  사용자가 직접 추가한 식단이면 null", null=True
            ),
        ),
        migrations.AddField(
            model_name="detailofdiet",
            name="image_y_end",
            field=models.IntegerField(
                blank=True, db_comment="이미지의 y 끝좌표,  사용자가 직접 추가한 식단이면 null", null=True
            ),
        ),
        migrations.AddField(
            model_name="detailofdiet",
            name="image_y_start",
            field=models.IntegerField(
                blank=True, db_comment="이미지의 y 시작좌표,  사용자가 직접 추가한 식단이면 null", null=True
            ),
        ),
    ]
