# Generated by Django 5.0 on 2024-02-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0003_remove_detailofdiet_image_x_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="food",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="food",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="food",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="food",
            name="image_path",
        ),
        migrations.RemoveField(
            model_name="food",
            name="updated_at",
        ),
    ]
