# Generated by Django 5.0.1 on 2024-02-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0005_remove_detailofdiet_image_x_end_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdiet",
            old_name="take_at",
            new_name="take_date",
        ),
    ]
