# Generated by Django 5.0.1 on 2024-02-21 02:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diet", "0006_rename_take_at_userdiet_take_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdiet",
            name="take_at",
            field=models.DateTimeField(
                db_comment="식단을 섭취한 날짜 및 시간",
                default=datetime.datetime(2024, 2, 21, 11, 22, 18, 283415),
            ),
        ),
    ]
