# Generated by Django 5.0 on 2024-02-03 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("terms_agree", models.BooleanField(default=True)),
                ("agree_of_marketing", models.BooleanField(default=False)),
                ("nickname", models.CharField(max_length=20)),
                ("sex", models.IntegerField(db_comment="1은 남성, 2는 여성", default=1)),
                ("birth", models.DateField()),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("goal_weight", models.IntegerField()),
                (
                    "level_of_activity",
                    models.IntegerField(
                        db_comment="1은 앉아서 일하는 경우, 2는 가벼운 활동을 하는 경우, 3은 보통 활동을 하는 경우, 4는 매우 활동적인 경우",
                        default=1,
                    ),
                ),
                ("recommend_daily_calorie", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
