# Generated by Django 5.0.1 on 2024-02-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="agree_of_marketing",
            new_name="agree_marketing_consent",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="terms_agree",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agree_age_confirmation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agree_privacy_policy",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="agree_terms_of_service",
            field=models.BooleanField(default=False),
        ),
    ]
