# Generated by Django 5.0.1 on 2024-02-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "user",
            "0002_rename_agree_of_marketing_userprofile_agree_marketing_consent_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="goal_weight",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="recommend_daily_calorie",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.IntegerField(null=True),
        ),
    ]
