# Generated by Django 5.0.1 on 2024-02-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_userprofile_birth_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="sex",
            new_name="gender",
        ),
    ]
