# Generated by Django 5.0.1 on 2024-02-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_rename_sex_userprofile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="goal_weight",
        ),
    ]
